config/routes.rb
Rails.application.routes.draw do

  get '/', to: redirect("/#{I18n.default_locale}")
  scope "/:locale" do 
  devise_for :users
  resources :friends
  get 'home/friends'
  root 'home#index'

end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord

    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
  
class ApplicationController < ActionController::Base
    before_action :set_locale
  
      def set_locale
        # Remove inappropriate/unnecessary ones
            I18n.locale = params[:locale] || # Request parameter
                      session[:locale] || # Current session
                      extract_locale_from_accept_language_header || # Language header - browser config
                      I18n.default_locale # Set in your config files, english by super-default
      end
  
      def default_url_options
        {locale: I18n.locale}
      end
  
  end    

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user
  @friend = current_user.friends.find_by(id: params[:id])
  redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row">
  <div class="field input-field col s6">
  <i class="material-icons prefix">account_circle</i>
    <%= form.label :first_name %>
    <%= form.text_field :first_name,class:"validate" %>
  </div>

  <div class="field input-field col s6">
    <%= form.label :last_name %>
    <%= form.text_field :last_name,class:"validate" %>
  </div>
</div>
  <div class="field input-field col s12">
     <i class="material-icons prefix">email</i>
    <%= form.label :email %>
    <%= form.text_field :email,class:"validate" %>
  </div>
 <div class="row">
  <div class="field input-field col s6">
    <i class="material-icons prefix">phone</i>
    <%= form.label :phone %>
    <%= form.text_field :phone,class:"validate" %>
  </div>

  <div class="field input-field col s6">
  <i class="material-icons prefix">format_quote</i>
    <%= form.label :twitter %>
    <%= form.text_field :twitter,class:"validate" %>
  </div>
    <div class="field input-field col s12">
    <%= form.text_field :user_id,id: :friend_user_id, class:"validate" , value: current_user.id ,type: :hidden %>
  </div>
</div>
  <div class="actions">
    <%= form.submit class:"waves-effect waves-teal btn"%>
  </div>
<% end %>

<style>
.btn{
  background-color: #006064;
}
</style>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>
<br>

<br>
<%= link_to 'Show', @friend  , class:"waves-effect waves-teal btn"%> |
<%= link_to 'Back', friends_path,class:"waves-effect waves-teal btn" %>

<style>

.btn:nth-child(odd){
  background-color: #006064;
}

</style>

app/views/friends/index.html.erb
<table class="responsive-table highlight centered">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
    <% if current_user == friend.user %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
    
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path,class:"waves-effect waves-teal btn" %>
<style>
.btn{
  background-color: #37474f;
}
</style>

app/views/friends/new.html.erb
<h1>Add new friend</h1>

<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path,class:"waves-effect waves-teal btn" %>
<style>
.btn{
  background-color: #006064;
}
</style>

app/views/friends/show.html.erb
 <div class="row">
    <div class="s12 m4 l8">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> <strong><h1>Friend Info</h1></strong></span>
          <hr>
         
<p> <h5> 
  <strong>First name:</strong>
  <%= @friend.first_name %></h5>
</p>

<br>

<p><h5> 
  <strong>Last name:</strong>
  <%= @friend.last_name %></h5>
</p>

<br>


<p><h5> 
  <strong>Email:</strong>
  <%= @friend.email %></h5>
</p>

<br>


<p><h5> 
  <strong>Phone:</strong>
  <%= @friend.phone %></h5>
</p>

<br>


<p><h5> 
  <strong>Twitter:</strong>
  <%= @friend.twitter %></h5>
</p>
        </div>
        <div class="card-action">
         <%= link_to 'Edit', edit_friend_path(@friend), class:"waves-effect waves-teal btn" %> |
          <%= link_to 'Back', friends_path ,class:"waves-effect waves-teal btn" %>
        </div>
      </div>
    </div>
  </div>

<style>
.btn:nth-child(odd){
  background-color: #37474f;
}
.btn:nth-child(even){
  background-color: #006064;
}
</style>

app/views/home/_header.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<script>
	$(document).ready(function(){
 		$('.sidenav').sidenav();
 	});

</script>

<nav>
    <div class="nav-wrapper blue-grey darken-1" >
      <%= link_to "Ayman's Blog", root_path, class:"brand-logo center" %>


		<a href="#" class="sidenav-trigger" data-target="mobile-nav">
			<i class="material-icons">menu</i>
		</a>

      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <% if user_signed_in?%>
                    <li> <%= link_to translate('.friends'), friends_path, class:"left hide-on-med-and-down" %></li>
                    <li><%= link_to translate('.newfriend'),  new_friend_path, class:"left hide-on-med-and-down" %></li>
                    <li><%= link_to translate('.signout'), destroy_user_session_path,method: :delete, class:"left hide-on-med-and-down" %></li>
                    <li><%= link_to translate('.editprofile'),  edit_user_registration_path, class:"left hide-on-med-and-down" %></li>
            <% else %>
                <li><%= link_to translate('.signup'),new_user_registration_path, class:"left hide-on-med-and-down" %></li>
                    <li><%= link_to translate('.signin'), new_user_session_path,class:"left hide-on-med-and-down" %></li>
             <% end %>
      </ul>
    </div>
  </nav>

 <ul class="sidenav" id="mobile-nav"> 
     <% if user_signed_in?%>
                    <li> <%= link_to translate('.friends'), friends_path %></li>
                    <li><%= link_to translate('.newfriend'),  new_friend_path %></li>
                    <li><%= link_to translate('.signout'), destroy_user_session_path,method: :delete %></li>
                    <li><%= link_to translate('.editprofile'),  edit_user_registration_path %></li>
            <% else %>
                     <li><%= link_to translate('.signup'),new_user_registration_path%></li>
                    <li><%= link_to translate('.signin'), new_user_session_path %></li>
             <% end %>
 </ul>

app/views/home/friends.html.erb
<h1> Friends us</h1>

app/views/home/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
.fa {
  padding: 15px;
  font-size: 15px;
  text-align: center;
  text-decoration: none;
  margin: 5px 5px 5px 5px;
  border-radius: 50%;
}

.fa:hover {
    opacity: 0.7;
}

.fa-twitter {
  background: #55ACEE;
  color: white;
}

.fa-linkedin {
  background: #007bb5;
  color: white;
}

.fa-reddit {
  background: #ff5700;
  color: white;
}

</style>



<div class="row">        <!-- create the row -->
  <div class="col s6">
    <div class="card blue-grey lighten-4">  <!-- create the card -->
      <div class="card-image">              <!-- card image -->
        <%= image_tag "me.jpg" %>     <!-- img -->
   
      </div>
        
      <div class="card-content">            <!-- card text -->
        <p>“The road may be long, tortuous and wearied. But the resulting success is enduring, sure and sweet. The fool abandons hope in the wearied journey of life. The wise gets going - holding firmly to the promise of a better tomorrow. He that gives up too soon fails to understand that life rewards with success only those who cling on to hope against hope. Those who hope when it is unfashionable to hope.”<br><br> ― Abiodun Fijabi </p>
      </div>
    </div>
  </div>
  <div class="col s6">   <!-- create the second column div -->
    <h3 style=" border: 1px solid black;
    background-color: black;
       font-size: 2.5em;
    font-weight: bold;
    letter-spacing: 11px;
    text-align: center;
    color: white;
    ">HI I'AM AYMAN</h3>
    <br>
 <section class="questions-section">
    <h5>More About Me</h5>
    <p>Because programming is awesome and programming for the internet is even more awesome.</p>
    <h5>What are your favorite hobbies?</h5>
    <p>My favorite hobby is building things on the internet like ecommerce sites and email marketing campaigns.</p>
    <h5>What's your dream job?</h5>
    <p>My dream job is similar to my current job except I would like to be building software instead of buildings.</p>
    <h5>Where do you live?</h5>
    <p>I live on a rural acreage, but I'm close to Ottawa and Montreal.</p>
    <h5>Why do you want to be a web developer?</h5>
    <p>Because programming is awesome and programming for the internet is even more awesome.</p>
</section>
<br><br><br>
<a href="https://twitter.com/Lyvant_" class="fa fa-twitter"></a>
<a href="https://www.linkedin.com/in/ayman-butmah-816b361b3/" class="fa fa-linkedin"></a>
<a href="https://www.reddit.com/" class="fa fa-reddit"></a>
  </div>
</div>

  

app/views/layouts/_alerts.html.erb
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  <%= notice %>.
</div>



<style>
.alert {
  padding: 20px;
  background-color: #ffb366;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
</style>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

     <title>Ayman's Blog | Task 2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>

<%= render "home/header" %>



  <div class="container"> 
  <br>

<% if notice%>
<%= render "layouts/alerts" %>
<% end %>

    <%= yield %>
  </div>                  
</body>
</html>